import './globals.css'
import { Rubik } from 'next/font/google'

// Components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

// We can put our <Nav/> files and footer files in this layout file

// meta day creation in every page
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// layout components wrap page components. children=pages
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
